[2024-09-15 20:04:18,817] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:04:18,821] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:04:18,821] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:18,821] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:18,821] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:18,831] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-18 00:00:00+00:00
[2024-09-15 20:04:18,834] {standard_task_runner.py:52} INFO - Started process 11585 to run task
[2024-09-15 20:04:18,836] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-18T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpisrz6_1v', '--error-file', '/tmp/tmpry3n6v0v']
[2024-09-15 20:04:18,836] {standard_task_runner.py:80} INFO - Job 60: Subtask BRONZE_TSLA
[2024-09-15 20:04:18,864] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:18,902] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-18T00:00:00+00:00
[2024-09-15 20:04:18,903] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:18,905] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240118T000000, start_date=20240915T230418, end_date=20240915T230418
[2024-09-15 20:04:18,914] {standard_task_runner.py:92} ERROR - Failed to execute job 60 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 11585)
[2024-09-15 20:04:18,929] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:18,938] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:07:54,317] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:07:54,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:07:54,323] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:54,323] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:07:54,323] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:54,334] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-18 00:00:00+00:00
[2024-09-15 20:07:54,337] {standard_task_runner.py:52} INFO - Started process 12408 to run task
[2024-09-15 20:07:54,339] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-18T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpizbvykfq', '--error-file', '/tmp/tmp0998etf7']
[2024-09-15 20:07:54,339] {standard_task_runner.py:80} INFO - Job 67: Subtask BRONZE_TSLA
[2024-09-15 20:07:54,372] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:07:54,419] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-18T00:00:00+00:00
[2024-09-15 20:07:57,426] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-15 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705294800, endDate = 1704258000")
[2024-09-15 20:07:57,428] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:07:57,432] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240118T000000, start_date=20240915T230754, end_date=20240915T230757
[2024-09-15 20:07:57,449] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:07:57,460] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:07:57,464] {dagrun.py:562} INFO - Marking run <DagRun BRONZER_GET_STONCKS @ 2024-01-18 00:00:00+00:00: scheduled__2024-01-18T00:00:00+00:00, externally triggered: False> successful
[2024-09-15 20:07:57,465] {dagrun.py:607} INFO - DagRun Finished: dag_id=BRONZER_GET_STONCKS, execution_date=2024-01-18 00:00:00+00:00, run_id=scheduled__2024-01-18T00:00:00+00:00, run_start_date=2024-09-15 23:07:38.844903+00:00, run_end_date=2024-09-15 23:07:57.465096+00:00, run_duration=18.620193, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-01-18 00:00:00+00:00, data_interval_end=2024-01-19 00:00:00+00:00, dag_hash=d881e529ddca44bbc90b852447cd3348
[2024-09-15 20:11:18,648] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:11:18,653] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:11:18,653] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:18,653] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:18,653] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:18,663] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-18 00:00:00+00:00
[2024-09-15 20:11:18,666] {standard_task_runner.py:52} INFO - Started process 12913 to run task
[2024-09-15 20:11:18,668] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-18T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp27zguxrb', '--error-file', '/tmp/tmppyzeutmz']
[2024-09-15 20:11:18,669] {standard_task_runner.py:80} INFO - Job 111: Subtask BRONZE_TSLA
[2024-09-15 20:11:18,696] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:18,737] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-18T00:00:00+00:00
[2024-09-15 20:11:18,738] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:11:18,740] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240118T000000, start_date=20240915T231118, end_date=20240915T231118
[2024-09-15 20:11:18,750] {standard_task_runner.py:92} ERROR - Failed to execute job 111 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 12913)
[2024-09-15 20:11:18,761] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:11:18,787] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:49,318] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:13:49,325] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:13:49,326] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:49,326] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:13:49,326] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:49,339] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-18 00:00:00+00:00
[2024-09-15 20:13:49,342] {standard_task_runner.py:52} INFO - Started process 13522 to run task
[2024-09-15 20:13:49,345] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-18T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzkx6z2ts', '--error-file', '/tmp/tmpmibwg03r']
[2024-09-15 20:13:49,346] {standard_task_runner.py:80} INFO - Job 111: Subtask BRONZE_TSLA
[2024-09-15 20:13:49,381] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:13:49,427] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-18T00:00:00+00:00
[2024-09-15 20:13:53,976] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-15 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705294800, endDate = 1704258000")
[2024-09-15 20:13:53,979] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:13:53,983] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240118T000000, start_date=20240915T231349, end_date=20240915T231353
[2024-09-15 20:13:54,023] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:13:54,034] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:54,039] {dagrun.py:547} ERROR - Marking run <DagRun BRONZER_GET_STONCKS @ 2024-01-18 00:00:00+00:00: scheduled__2024-01-18T00:00:00+00:00, externally triggered: False> failed
[2024-09-15 20:13:54,040] {dagrun.py:607} INFO - DagRun Finished: dag_id=BRONZER_GET_STONCKS, execution_date=2024-01-18 00:00:00+00:00, run_id=scheduled__2024-01-18T00:00:00+00:00, run_start_date=2024-09-15 23:13:36.487327+00:00, run_end_date=2024-09-15 23:13:54.040274+00:00, run_duration=17.552947, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2024-01-18 00:00:00+00:00, data_interval_end=2024-01-19 00:00:00+00:00, dag_hash=d881e529ddca44bbc90b852447cd3348
[2024-09-15 20:18:55,387] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:18:55,392] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [queued]>
[2024-09-15 20:18:55,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:55,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:18:55,392] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:55,403] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-18 00:00:00+00:00
[2024-09-15 20:18:55,405] {standard_task_runner.py:52} INFO - Started process 14179 to run task
[2024-09-15 20:18:55,408] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-18T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp9quypt5i', '--error-file', '/tmp/tmpczh3op78']
[2024-09-15 20:18:55,408] {standard_task_runner.py:80} INFO - Job 111: Subtask BRONZE_TSLA
[2024-09-15 20:18:55,437] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-18T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:18:55,476] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-18T00:00:00+00:00
[2024-09-15 20:18:58,730] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-15 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705294800, endDate = 1704258000")
[2024-09-15 20:18:58,733] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:18:58,737] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240118T000000, start_date=20240915T231855, end_date=20240915T231858
[2024-09-15 20:18:58,768] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:18:58,779] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
