[2024-09-15 20:02:55,987] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:02:55,992] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:02:55,992] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:55,992] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:55,992] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:56,003] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:02:56,005] {standard_task_runner.py:52} INFO - Started process 11259 to run task
[2024-09-15 20:02:56,007] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpbvm17ryq', '--error-file', '/tmp/tmpz9gzeqlq']
[2024-09-15 20:02:56,008] {standard_task_runner.py:80} INFO - Job 25: Subtask BRONZE_AAPL
[2024-09-15 20:02:56,040] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:56,079] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:02:59,635] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-05 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704430800, endDate = 1704258000")
[2024-09-15 20:02:59,642] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:59,652] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240106T000000, start_date=20240915T230255, end_date=20240915T230259
[2024-09-15 20:02:59,683] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:59,693] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:16,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:16,285] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:16,285] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:16,285] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:16,285] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:16,295] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:06:16,298] {standard_task_runner.py:52} INFO - Started process 11979 to run task
[2024-09-15 20:06:16,301] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpd21gkg6b', '--error-file', '/tmp/tmp_mi9nlfc']
[2024-09-15 20:06:16,301] {standard_task_runner.py:80} INFO - Job 27: Subtask BRONZE_AAPL
[2024-09-15 20:06:16,330] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:16,371] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:06:16,372] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:16,375] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240106T000000, start_date=20240915T230616, end_date=20240915T230616
[2024-09-15 20:06:16,383] {standard_task_runner.py:92} ERROR - Failed to execute job 27 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 11979)
[2024-09-15 20:06:16,394] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:16,405] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:07,871] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:07,876] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:07,876] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:07,876] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:07,876] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:07,886] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:09:07,889] {standard_task_runner.py:52} INFO - Started process 12570 to run task
[2024-09-15 20:09:07,891] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpo5529242', '--error-file', '/tmp/tmpg42vfrni']
[2024-09-15 20:09:07,892] {standard_task_runner.py:80} INFO - Job 76: Subtask BRONZE_AAPL
[2024-09-15 20:09:07,924] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:07,968] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:09:08,484] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:09:08,486] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:08,491] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240106T000000, start_date=20240915T230907, end_date=20240915T230908
[2024-09-15 20:09:08,506] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:08,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:50,511] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:50,516] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:50,516] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:50,516] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:50,516] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:50,528] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:12:50,531] {standard_task_runner.py:52} INFO - Started process 13197 to run task
[2024-09-15 20:12:50,533] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpgrvidd96', '--error-file', '/tmp/tmpa7h_0wpt']
[2024-09-15 20:12:50,533] {standard_task_runner.py:80} INFO - Job 76: Subtask BRONZE_AAPL
[2024-09-15 20:12:50,561] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:50,601] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:12:50,602] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:50,605] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240106T000000, start_date=20240915T231250, end_date=20240915T231250
[2024-09-15 20:12:50,614] {standard_task_runner.py:92} ERROR - Failed to execute job 76 for task BRONZE_AAPL ([Errno 13] Permission denied: '/Documents'; 13197)
[2024-09-15 20:12:50,625] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:50,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:06,711] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:06,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:06,716] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:06,716] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:06,716] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:06,728] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:16:06,730] {standard_task_runner.py:52} INFO - Started process 13849 to run task
[2024-09-15 20:16:06,732] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpyebaq478', '--error-file', '/tmp/tmpz8cyt8wk']
[2024-09-15 20:16:06,733] {standard_task_runner.py:80} INFO - Job 76: Subtask BRONZE_AAPL
[2024-09-15 20:16:06,761] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:06,833] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:16:07,467] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:16:07,470] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:07,474] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240106T000000, start_date=20240915T231606, end_date=20240915T231607
[2024-09-15 20:16:07,508] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:07,519] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
