[2024-09-15 20:03:05,732] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:05,736] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:05,736] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:05,736] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:03:05,736] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:05,746] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:03:05,749] {standard_task_runner.py:52} INFO - Started process 11277 to run task
[2024-09-15 20:03:05,751] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmphd_kpdvp', '--error-file', '/tmp/tmprx8as3by']
[2024-09-15 20:03:05,751] {standard_task_runner.py:80} INFO - Job 27: Subtask BRONZE_GOOG
[2024-09-15 20:03:05,778] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:03:05,816] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:03:09,017] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-05 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704430800, endDate = 1704258000")
[2024-09-15 20:03:09,019] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:03:09,023] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240106T000000, start_date=20240915T230305, end_date=20240915T230309
[2024-09-15 20:03:09,069] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:03:09,079] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:18,744] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:18,749] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:18,749] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:18,749] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:18,749] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:18,760] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:06:18,762] {standard_task_runner.py:52} INFO - Started process 11997 to run task
[2024-09-15 20:06:18,764] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpbz4pbkw9', '--error-file', '/tmp/tmpvwbicd1b']
[2024-09-15 20:06:18,765] {standard_task_runner.py:80} INFO - Job 29: Subtask BRONZE_GOOG
[2024-09-15 20:06:18,792] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:18,829] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:06:18,830] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:18,832] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240106T000000, start_date=20240915T230618, end_date=20240915T230618
[2024-09-15 20:06:18,840] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task BRONZE_GOOG ([Errno 13] Permission denied: '/datalake'; 11997)
[2024-09-15 20:06:18,857] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:18,866] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:11,584] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:11,589] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:11,589] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:11,589] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:11,589] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:11,600] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:09:11,602] {standard_task_runner.py:52} INFO - Started process 12588 to run task
[2024-09-15 20:09:11,605] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmps8ech5vu', '--error-file', '/tmp/tmp74ri2mj7']
[2024-09-15 20:09:11,605] {standard_task_runner.py:80} INFO - Job 78: Subtask BRONZE_GOOG
[2024-09-15 20:09:11,634] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:11,674] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:09:12,211] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:09:12,214] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:12,218] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240106T000000, start_date=20240915T230911, end_date=20240915T230912
[2024-09-15 20:09:12,260] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:12,270] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:53,231] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:53,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:53,237] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:53,237] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:53,237] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:53,249] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:12:53,253] {standard_task_runner.py:52} INFO - Started process 13217 to run task
[2024-09-15 20:12:53,255] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpuge0jjcg', '--error-file', '/tmp/tmp9rwjkojw']
[2024-09-15 20:12:53,255] {standard_task_runner.py:80} INFO - Job 78: Subtask BRONZE_GOOG
[2024-09-15 20:12:53,286] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:53,330] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:12:53,330] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:53,333] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240106T000000, start_date=20240915T231253, end_date=20240915T231253
[2024-09-15 20:12:53,343] {standard_task_runner.py:92} ERROR - Failed to execute job 78 for task BRONZE_GOOG ([Errno 13] Permission denied: '/Documents'; 13217)
[2024-09-15 20:12:53,348] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:53,359] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:10,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:10,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:10,775] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:10,775] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:10,775] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:10,786] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:16:10,789] {standard_task_runner.py:52} INFO - Started process 13869 to run task
[2024-09-15 20:16:10,791] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpola1cnzk', '--error-file', '/tmp/tmpf9ime0nu']
[2024-09-15 20:16:10,791] {standard_task_runner.py:80} INFO - Job 78: Subtask BRONZE_GOOG
[2024-09-15 20:16:10,822] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:10,862] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:16:11,623] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:16:11,629] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:11,637] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240106T000000, start_date=20240915T231610, end_date=20240915T231611
[2024-09-15 20:16:11,689] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:11,701] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
