[2024-09-15 20:03:10,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:10,215] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:10,215] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:10,215] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:03:10,215] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:10,226] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:03:10,228] {standard_task_runner.py:52} INFO - Started process 11286 to run task
[2024-09-15 20:03:10,230] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpcrog35_w', '--error-file', '/tmp/tmprqa4zih8']
[2024-09-15 20:03:10,231] {standard_task_runner.py:80} INFO - Job 28: Subtask BRONZE_TSLA
[2024-09-15 20:03:10,259] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:03:10,298] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:03:13,466] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-05 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704430800, endDate = 1704258000")
[2024-09-15 20:03:13,469] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:03:13,473] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240106T000000, start_date=20240915T230310, end_date=20240915T230313
[2024-09-15 20:03:13,507] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:03:13,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:19,975] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:19,979] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:19,979] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:19,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:19,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:19,989] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:06:19,991] {standard_task_runner.py:52} INFO - Started process 12006 to run task
[2024-09-15 20:06:19,993] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp4pr2fgty', '--error-file', '/tmp/tmp4ek8wy7k']
[2024-09-15 20:06:19,994] {standard_task_runner.py:80} INFO - Job 30: Subtask BRONZE_TSLA
[2024-09-15 20:06:20,021] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:20,058] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:06:20,059] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:20,061] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240106T000000, start_date=20240915T230619, end_date=20240915T230620
[2024-09-15 20:06:20,069] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 12006)
[2024-09-15 20:06:20,086] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:20,095] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:13,481] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:13,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:13,487] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:13,487] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:13,487] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:13,497] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:09:13,500] {standard_task_runner.py:52} INFO - Started process 12597 to run task
[2024-09-15 20:09:13,502] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpb1e8epsz', '--error-file', '/tmp/tmp38rl37ai']
[2024-09-15 20:09:13,503] {standard_task_runner.py:80} INFO - Job 79: Subtask BRONZE_TSLA
[2024-09-15 20:09:13,533] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:13,573] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:09:14,106] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:09:14,109] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:14,113] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240106T000000, start_date=20240915T230913, end_date=20240915T230914
[2024-09-15 20:09:14,158] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:14,168] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:54,537] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:54,542] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:54,543] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:54,543] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:54,543] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:54,554] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:12:54,557] {standard_task_runner.py:52} INFO - Started process 13226 to run task
[2024-09-15 20:12:54,559] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp8wnptor3', '--error-file', '/tmp/tmpv8yniugs']
[2024-09-15 20:12:54,559] {standard_task_runner.py:80} INFO - Job 79: Subtask BRONZE_TSLA
[2024-09-15 20:12:54,587] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:54,626] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:12:54,627] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:54,629] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240106T000000, start_date=20240915T231254, end_date=20240915T231254
[2024-09-15 20:12:54,638] {standard_task_runner.py:92} ERROR - Failed to execute job 79 for task BRONZE_TSLA ([Errno 13] Permission denied: '/Documents'; 13226)
[2024-09-15 20:12:54,652] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:54,663] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:12,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:12,895] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:12,895] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:12,895] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:12,895] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:12,907] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:16:12,909] {standard_task_runner.py:52} INFO - Started process 13878 to run task
[2024-09-15 20:16:12,912] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpy2gcv2mi', '--error-file', '/tmp/tmp_ek98jsv']
[2024-09-15 20:16:12,912] {standard_task_runner.py:80} INFO - Job 79: Subtask BRONZE_TSLA
[2024-09-15 20:16:12,940] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:12,980] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:16:13,573] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:16:13,579] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:13,588] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240106T000000, start_date=20240915T231612, end_date=20240915T231613
[2024-09-15 20:16:13,609] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:13,620] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
