[2024-09-15 20:04:23,033] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:04:23,037] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:04:23,037] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:23,037] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:23,037] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:23,047] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:04:23,050] {standard_task_runner.py:52} INFO - Started process 11613 to run task
[2024-09-15 20:04:23,052] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpuatetdi9', '--error-file', '/tmp/tmpckhhq5s5']
[2024-09-15 20:04:23,052] {standard_task_runner.py:80} INFO - Job 63: Subtask BRONZE_GOOG
[2024-09-15 20:04:23,082] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:23,122] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:04:23,122] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:23,125] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240119T000000, start_date=20240915T230423, end_date=20240915T230423
[2024-09-15 20:04:23,133] {standard_task_runner.py:92} ERROR - Failed to execute job 63 for task BRONZE_GOOG ([Errno 13] Permission denied: '/datalake'; 11613)
[2024-09-15 20:04:23,144] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:23,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:11:23,583] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:11:23,588] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:11:23,588] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:23,589] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:23,589] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:23,599] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:11:23,602] {standard_task_runner.py:52} INFO - Started process 12945 to run task
[2024-09-15 20:11:23,604] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpfvdb5ztj', '--error-file', '/tmp/tmpjuke0lpo']
[2024-09-15 20:11:23,605] {standard_task_runner.py:80} INFO - Job 114: Subtask BRONZE_GOOG
[2024-09-15 20:11:23,634] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:23,676] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:11:28,677] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-16 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705381200, endDate = 1704258000")
[2024-09-15 20:11:28,679] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:11:28,683] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240119T000000, start_date=20240915T231123, end_date=20240915T231128
[2024-09-15 20:11:28,713] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:11:28,720] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:19:10,865] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:19:10,870] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:19:10,870] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:10,870] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:19:10,870] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:10,880] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:19:10,883] {standard_task_runner.py:52} INFO - Started process 14206 to run task
[2024-09-15 20:19:10,886] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzk6mlxqt', '--error-file', '/tmp/tmpvotlrjxb']
[2024-09-15 20:19:10,886] {standard_task_runner.py:80} INFO - Job 114: Subtask BRONZE_GOOG
[2024-09-15 20:19:10,915] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:19:10,957] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:19:15,176] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-16 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705381200, endDate = 1704258000")
[2024-09-15 20:19:15,179] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:19:15,183] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240119T000000, start_date=20240915T231910, end_date=20240915T231915
[2024-09-15 20:19:15,215] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:19:15,230] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
