[2024-09-15 20:02:35,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:02:35,241] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:02:35,241] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:35,241] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:35,241] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:35,252] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:02:35,255] {standard_task_runner.py:52} INFO - Started process 11221 to run task
[2024-09-15 20:02:35,257] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp3uwnoq7y', '--error-file', '/tmp/tmpcuphgpi3']
[2024-09-15 20:02:35,257] {standard_task_runner.py:80} INFO - Job 21: Subtask BRONZE_AAPL
[2024-09-15 20:02:35,285] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:35,325] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:02:39,455] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-04 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704344400, endDate = 1704258000")
[2024-09-15 20:02:39,462] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:39,470] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T230235, end_date=20240915T230239
[2024-09-15 20:02:39,506] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:39,520] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:09,940] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:06:09,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:06:09,945] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:09,945] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:09,945] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:09,955] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:06:09,957] {standard_task_runner.py:52} INFO - Started process 11941 to run task
[2024-09-15 20:06:09,959] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp34f10ks1', '--error-file', '/tmp/tmp0jsyphx2']
[2024-09-15 20:06:09,960] {standard_task_runner.py:80} INFO - Job 23: Subtask BRONZE_AAPL
[2024-09-15 20:06:09,987] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:10,023] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:06:10,024] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:10,027] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T230609, end_date=20240915T230610
[2024-09-15 20:06:10,035] {standard_task_runner.py:92} ERROR - Failed to execute job 23 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 11941)
[2024-09-15 20:06:10,052] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:10,062] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:08:59,816] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:08:59,821] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:08:59,821] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:59,821] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:08:59,821] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:59,833] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:08:59,835] {standard_task_runner.py:52} INFO - Started process 12533 to run task
[2024-09-15 20:08:59,838] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpa07t5em8', '--error-file', '/tmp/tmpre3d5wzp']
[2024-09-15 20:08:59,838] {standard_task_runner.py:80} INFO - Job 72: Subtask BRONZE_AAPL
[2024-09-15 20:08:59,866] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:08:59,906] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:09:00,440] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:00,445] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T230859, end_date=20240915T230900
[2024-09-15 20:09:00,493] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:00,503] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:44,137] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:12:44,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:12:44,143] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:44,143] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:44,143] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:44,164] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:12:44,170] {standard_task_runner.py:52} INFO - Started process 13160 to run task
[2024-09-15 20:12:44,175] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmptpz9w7is', '--error-file', '/tmp/tmpoyqcsvu1']
[2024-09-15 20:12:44,176] {standard_task_runner.py:80} INFO - Job 72: Subtask BRONZE_AAPL
[2024-09-15 20:12:44,233] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:44,314] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:12:44,315] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:44,324] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T231244, end_date=20240915T231244
[2024-09-15 20:12:44,336] {standard_task_runner.py:92} ERROR - Failed to execute job 72 for task BRONZE_AAPL ([Errno 13] Permission denied: '/Documents'; 13160)
[2024-09-15 20:12:44,353] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:44,386] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:14:58,933] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:14:58,937] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:14:58,937] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:58,937] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:14:58,937] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:58,947] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:14:58,950] {standard_task_runner.py:52} INFO - Started process 13651 to run task
[2024-09-15 20:14:58,952] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpnuy4y9r6', '--error-file', '/tmp/tmphfa0bpul']
[2024-09-15 20:14:58,953] {standard_task_runner.py:80} INFO - Job 72: Subtask BRONZE_AAPL
[2024-09-15 20:14:58,980] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:14:59,027] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:14:59,715] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:14:59,720] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T231458, end_date=20240915T231459
[2024-09-15 20:14:59,770] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:14:59,779] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:15:58,612] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:15:58,619] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:15:58,619] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:58,619] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:15:58,619] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:58,632] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:15:58,635] {standard_task_runner.py:52} INFO - Started process 13812 to run task
[2024-09-15 20:15:58,639] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpye5oaqn7', '--error-file', '/tmp/tmprgb6e769']
[2024-09-15 20:15:58,640] {standard_task_runner.py:80} INFO - Job 72: Subtask BRONZE_AAPL
[2024-09-15 20:15:58,677] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:15:58,729] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:15:59,299] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:15:59,304] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240105T000000, start_date=20240915T231558, end_date=20240915T231559
[2024-09-15 20:15:59,334] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:15:59,351] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
