[2024-09-15 20:04:26,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:04:26,779] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:04:26,779] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:26,779] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:26,779] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:26,789] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-20 00:00:00+00:00
[2024-09-15 20:04:26,791] {standard_task_runner.py:52} INFO - Started process 11631 to run task
[2024-09-15 20:04:26,794] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-20T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpf0w9et03', '--error-file', '/tmp/tmplrd7j2ep']
[2024-09-15 20:04:26,794] {standard_task_runner.py:80} INFO - Job 65: Subtask BRONZE_AAPL
[2024-09-15 20:04:26,822] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:26,861] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-20T00:00:00+00:00
[2024-09-15 20:04:26,862] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:26,864] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240120T000000, start_date=20240915T230426, end_date=20240915T230426
[2024-09-15 20:04:26,872] {standard_task_runner.py:92} ERROR - Failed to execute job 65 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 11631)
[2024-09-15 20:04:26,886] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:26,898] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:11:35,965] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:11:35,969] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:11:35,969] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:35,969] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:35,969] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:35,985] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-20 00:00:00+00:00
[2024-09-15 20:11:35,987] {standard_task_runner.py:52} INFO - Started process 12963 to run task
[2024-09-15 20:11:35,990] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-20T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpmp4c1b14', '--error-file', '/tmp/tmpkifegwhh']
[2024-09-15 20:11:35,990] {standard_task_runner.py:80} INFO - Job 116: Subtask BRONZE_AAPL
[2024-09-15 20:11:36,018] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:36,057] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-20T00:00:00+00:00
[2024-09-15 20:11:39,399] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-17 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705467600, endDate = 1704258000")
[2024-09-15 20:11:39,408] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:11:39,419] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240120T000000, start_date=20240915T231135, end_date=20240915T231139
[2024-09-15 20:11:39,463] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:11:39,475] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:19:23,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:19:23,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [queued]>
[2024-09-15 20:19:23,884] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:23,884] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:19:23,884] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:23,993] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-20 00:00:00+00:00
[2024-09-15 20:19:24,012] {standard_task_runner.py:52} INFO - Started process 14229 to run task
[2024-09-15 20:19:24,016] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-20T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpovo7fnht', '--error-file', '/tmp/tmpl47jwvjq']
[2024-09-15 20:19:24,017] {standard_task_runner.py:80} INFO - Job 116: Subtask BRONZE_AAPL
[2024-09-15 20:19:24,119] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-20T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:19:24,314] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-20T00:00:00+00:00
[2024-09-15 23:27:49,559] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-17 -> 2024-01-03)
[2024-09-15 23:27:49,562] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 23:27:49,567] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240120T000000, start_date=20240915T231923, end_date=20240916T022749
[2024-09-15 23:27:49,616] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 23:27:49,623] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
