[2024-09-15 20:04:40,043] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-09-15 20:04:40,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-09-15 20:04:40,048] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:40,048] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:40,048] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:40,060] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-24 00:00:00+00:00
[2024-09-15 20:04:40,063] {standard_task_runner.py:52} INFO - Started process 11716 to run task
[2024-09-15 20:04:40,065] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-24T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp250jqq6y', '--error-file', '/tmp/tmpn7ri4n1q']
[2024-09-15 20:04:40,066] {standard_task_runner.py:80} INFO - Job 74: Subtask BRONZE_MSFT
[2024-09-15 20:04:40,096] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:40,139] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-24T00:00:00+00:00
[2024-09-15 20:04:40,140] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:40,142] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240124T000000, start_date=20240915T230440, end_date=20240915T230440
[2024-09-15 20:04:40,152] {standard_task_runner.py:92} ERROR - Failed to execute job 74 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 11716)
[2024-09-15 20:04:40,158] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:40,169] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 23:28:24,668] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-09-15 23:28:24,673] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-09-15 23:28:24,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 23:28:24,673] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 23:28:24,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 23:28:24,683] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-24 00:00:00+00:00
[2024-09-15 23:28:24,686] {standard_task_runner.py:52} INFO - Started process 14393 to run task
[2024-09-15 23:28:24,688] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-24T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp8x1kk17q', '--error-file', '/tmp/tmpklu64reb']
[2024-09-15 23:28:24,689] {standard_task_runner.py:80} INFO - Job 125: Subtask BRONZE_MSFT
[2024-09-15 23:28:24,717] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-24T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 23:28:24,759] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-24T00:00:00+00:00
[2024-09-15 23:28:27,159] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-21 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705813200, endDate = 1704258000")
[2024-09-15 23:28:27,161] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 23:28:27,165] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240124T000000, start_date=20240916T022824, end_date=20240916T022827
[2024-09-15 23:28:27,196] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 23:28:27,206] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
